replicaCount: 2

image:
  repository: ghcr.io/ldest/sre-course/api
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "c4f3862"
  
variables:
  ASPNETCORE_URLS: http://*:8081
  CONNECTIONSTRINGS__PGCONNECTION: server=91.185.86.249; port=5000; database=weather; user id=postgres; password=postgres-pass;

service:
  type: ClusterIP
  port: 8081

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount: {}

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

ingress:
  enabled: true
  className: "nginx"
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chumakov.weather-api.sre-course.example
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources:
   limits:
     cpu: 100m
     memory: 128Mi
   requests:
     cpu: 50m
     memory: 64Mi

autoscaling: {}

volumes: []

volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}
